version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.3
  telegram: uniqueck/telegram-orb@dev:alpha

jobs:
  statustest:
    executor: orb-tools/ubuntu
    steps:
      - run: exit 0
      - telegram/status

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [
    statustest-master
  ]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires: [orb-tools/lint]

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: uniqueck/telegram-orb
          requires: [orb-tools/pack]

      - orb-tools/trigger-integration-workflow:
          context: orb-publishing
          name: trigger-integration-dev
          ssh-fingerprints: 1b:ee:4d:0c:3b:b9:5c:96:b0:e6:0b:86:ec:f5:ae:ea
          cleanup-tags: true
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          ssh-fingerprints: 1b:ee:4d:0c:3b:b9:5c:96:b0:e6:0b:86:ec:f5:ae:ea
          cleanup-tags: true
          tag: master
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              only: master


  integration_tests-prod_deploy:
    jobs:
      # triggered by non-master branch commits
      - statustest:
          name: statustest-dev
          context: orb-publishing
          filters: *integration-dev_filters

      # triggered by master branch commits
      - statustest:
          name: statustest-master
          context: orb-publishing
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: uniqueck/telegram-orb
          cleanup-tags: true
          ssh-fingerprints: 1b:ee:4d:0c:3b:b9:5c:96:b0:e6:0b:86:ec:f5:ae:ea
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          release: minor
          context: orb-publishing
          orb-name: uniqueck/telegram-orb
          cleanup-tags: true
          ssh-fingerprints: 1b:ee:4d:0c:3b:b9:5c:96:b0:e6:0b:86:ec:f5:ae:ea
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          release: major
          context: orb-publishing
          orb-name: uniqueck/telegram-orb
          cleanup-tags: true
          ssh-fingerprints: 1b:ee:4d:0c:3b:b9:5c:96:b0:e6:0b:86:ec:f5:ae:ea
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
