version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.3
  telegram: uniqueck/telegram-orb@dev:alpha

jobs:
  statustest:
    executor: orb-tools/ubuntu
    steps:
      - run: exit 0
      - telegram/status

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires: [orb-tools/lint]

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: uniqueck/telegram-orb
          requires: [orb-tools/pack]

      - orb-tools/trigger-integration-workflow:
          context: orb-publishing
          name: trigger-integration-dev
          ssh-fingerprints: 1b:ee:4d:0c:3b:b9:5c:96:b0:e6:0b:86:ec:f5:ae:ea
          cleanup-tags: true
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              ignore: master
